name: TruffleHog Secret Scan

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  scan_secrets:
    name: Run TruffleHog Secret Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install TruffleHog
        run: |
          python3 -m pip install --upgrade pip
          pip install truffleHog

      - name: Run TruffleHog (Filesystem Scan)
        run: |
          echo "Running TruffleHog..."
          ls -al
          trufflehog --version
          trufflehog filesystem --directory . --json > trufflehog-report.json || {
            echo "TruffleHog scan failed! Showing debug information."
            exit 1
          }

      - name: Upload TruffleHog Report as Artifact (if exists)
        if: always() # Uploads the report even if the job fails
        uses: actions/upload-artifact@v3
        with:
          name: trufflehog-report
          path: trufflehog-report.json
          if-no-files-found: ignore

      - name: Display TruffleHog Findings (Optional)
        if: success()
        run: |
          cat trufflehog-report.json | jq '.'
