name: Trufflehog Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Install Trufflehog
    - name: Install Trufflehog
      run: |
        curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin
        trufflehog --version

    # Run Trufflehog Scan
    - name: Run Trufflehog Scan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        trufflehog git https://github.com/${{ github.repository }} --only-json > trufflehog-results.json

    # Upload the Results (Optional)
    - name: Upload Results
      uses: actions/upload-artifact@v3
      with:
        name: trufflehog-results
        path: trufflehog-results.json
